/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.jakubostapowiczsprawdzian;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author dell
 */
public class JakubOstapowicz extends javax.swing.JFrame {

    /**
     * Creates new form JakubOstapowicz
     */
    public JakubOstapowicz() {
        initComponents();
        addKeyListenerTojo_jTextFieldModel();
        addKeyListenerTojo_jTextFieldPartia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jo_jPanelMain = new javax.swing.JPanel();
        jo_jLabelSerialNumber = new javax.swing.JLabel();
        jo_jLabelModel = new javax.swing.JLabel();
        jo_jLabelPartia = new javax.swing.JLabel();
        jo_jTextFieldModel = new javax.swing.JTextField();
        jo_jTextFieldPartia = new javax.swing.JTextField();
        jo_jMenuBarMain = new javax.swing.JMenuBar();
        jo_jMenuFile = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jo_jPanelMain.setBackground(new java.awt.Color(204, 255, 204));

        jo_jLabelSerialNumber.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jo_jLabelSerialNumber.setText("Nr seryjny urządzenia");

        jo_jLabelModel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jo_jLabelModel.setText("Znak modelu");

        jo_jLabelPartia.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jo_jLabelPartia.setText("Nr partii");

        jo_jTextFieldModel.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jo_jTextFieldModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jo_jTextFieldModelActionPerformed(evt);
            }
        });

        jo_jTextFieldPartia.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jo_jPanelMainLayout = new javax.swing.GroupLayout(jo_jPanelMain);
        jo_jPanelMain.setLayout(jo_jPanelMainLayout);
        jo_jPanelMainLayout.setHorizontalGroup(
            jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                        .addComponent(jo_jLabelSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jo_jTextFieldModel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jo_jLabelModel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jo_jLabelPartia)
                            .addComponent(jo_jTextFieldPartia, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jo_jPanelMainLayout.setVerticalGroup(
            jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jo_jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jo_jLabelSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jo_jLabelModel)
                    .addComponent(jo_jLabelPartia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jo_jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jo_jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jo_jTextFieldPartia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jo_jMenuFile.setText("Plik");
        jo_jMenuBarMain.add(jo_jMenuFile);

        setJMenuBar(jo_jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jo_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jo_jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jo_jTextFieldModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jo_jTextFieldModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jo_jTextFieldModelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JakubOstapowicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JakubOstapowicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JakubOstapowicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JakubOstapowicz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JakubOstapowicz().setVisible(true);
            }
        });
    }
    
    public void addKeyListenerTojo_jTextFieldModel(){
        jo_jTextFieldModel.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch == 'o' || ch == 'p' || ch == 'r' || ch == 's' || ch == 't' || ch == 'u' || ch == KeyEvent.VK_BACK_SPACE){
                    jo_jTextFieldModel.setEditable(true);
                }
                jo_jTextFieldModel.setEditable(false);
                
            }

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
        
    }
    
    public void addKeyListenerTojo_jTextFieldPartia(){
        jo_jTextFieldPartia.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                char ch = e.getKeyChar();
                if(ch >= '0' && ch <= '9' || ch == KeyEvent.VK_BACK_SPACE){
                    jo_jTextFieldPartia.setEditable(true);
                }
                jo_jTextFieldPartia.setEditable(false);
            }
                

            @Override
            public void keyPressed(KeyEvent e) {
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jo_jLabelModel;
    private javax.swing.JLabel jo_jLabelPartia;
    private javax.swing.JLabel jo_jLabelSerialNumber;
    private javax.swing.JMenuBar jo_jMenuBarMain;
    private javax.swing.JMenu jo_jMenuFile;
    private javax.swing.JPanel jo_jPanelMain;
    private javax.swing.JTextField jo_jTextFieldModel;
    private javax.swing.JTextField jo_jTextFieldPartia;
    // End of variables declaration//GEN-END:variables
}
